---
name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: docker/setup-buildx-action@v1
        name: buildx

      - uses: docker/login-action@v1
        name: docker login
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/diegosteiner/db-backup:latest
